import KeyMirror from 'keymirror'

export default KeyMirror({
  CHANGE_ORGANIZATION: null,
  CHANGE_REPOSITORY: null,
  LOAD_REPOSITORIES: null,
  LOAD_REPOSITORIES_COMPLETED: null,
  LOAD_PULL_REQUESTS: null,
  LOAD_PULL_REQUESTS_COMPLETED: null,
  LOAD_COMMENTS: null,
  LOAD_COMMENTS_COMPLETED: null,
  LOAD_ISSUE_COMMENTS: null,
  LOAD_ISSUE_COMMENTS_COMPLETED: null,
  LOAD_COMMITS: null,
  LOAD_COMMITS_COMPLETED: null,
  LOAD_ORGANIZATIONS: null,
  LOAD_ORGANIZATIONS_COMPLETED: null,
  ERROR: null,
  LOAD_PREFERENCE: null,
  CHANGE_PREFERENCE: null,
  CLICK_PREFERENCE_BUTTON: null
})
